from heap_priority_queue import HeapPriorityQueue

heap = HeapPriorityQueue()
heap.add(3, 'b')
print(heap._data)
heap.add(6, 'b')
print(heap._data)
heap.add(1, 'a')
print(heap._data)
heap.add(5, 'g')
print(heap._data)
heap.add(2, 't')
print(heap._data)
heap.add(4, 'p')
print(heap._data)
heap.remove_min()
print(heap._data)
heap.remove_min()
print(heap._data)
heap.remove_min()
print(heap._data)
heap.remove_min()
print(heap._data)
